---
name:
on:
  - push
###  push:
###    branches:
###      github_test


jobs:
  examine_contexts:
    name: 'Examine Context contents'
    if: always()
    runs-on: ubuntu-16.04
    steps:
      - name: Dump contexts
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump needs context
        env:
          ENV_CONTEXT: ${{ toJson(needs) }}
        run: echo "$ENV_CONTEXT"
      - name: Dump env vars
        run: env | sort

